
spring:
  datasource:
    url: jdbc:postgresql://ec2-34-200-158-205.compute-1.amazonaws.com:5432/d4l15ha0q7fik6?user=fbjfnxqsalkevb&password=60529efc8c3ca43e7ed398776fc98c3978e6c8c194c7c1f58b0eb66634f3f78c&stringtype=unspecified
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  error:
    whitelabel:
      enabled: false
    include-stacktrace: always

